openapi: 3.0.0
info:
  title: Plant.ly API
  version: v1
  description: API para monitoramento de plantas.
servers:
  - url: http://localhost:3030
    description: Servidor local para a API

tags:
  - name: users
    description: Endpoints relacionados aos usuários
  - name: auth
    description: Endpoints relacionados à autenticação
  - name: plants
    description: Endpoints relacionados às plantas
  - name: sensors
    description: Endpoints relacionados aos dados dos sensores

paths:
  /v1/users:
    post:
      tags:
        - users
      summary: Criação de novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        201:
          description: Usuário criado com sucesso.
        400:
          description: Requisição inválida.
        500:
          description: Erro interno do servidor.

  /v1/sensors:
    get:
      tags:
        - sensors
      summary: Obter dados dos sensores
      parameters:
        - name: plantid
          in: query
          required: true
          schema:
            type: string
            description: ID da planta.
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
        - name: week
          in: query
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
            default: 100
      responses:
        200:
          description: Dados dos sensores retornados com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorData'
        400:
          description: Parâmetros inválidos.
        500:
          description: Erro no servidor.

  /v1/sensors/last:
    get:
      tags:
        - sensors
      summary: Obter o último registro de sensores
      parameters:
        - name: plantid
          in: query
          required: true
          schema:
            type: string
            description: ID da planta.
      responses:
        200:
          description: Último registro retornado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorData'
        400:
          description: Parâmetros inválidos.
        500:
          description: Erro no servidor.

  /v1/sensors/average:
    get:
      tags:
        - sensors
      summary: Obter média dos dados
      parameters:
        - name: plantid
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Média calculada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  averageTemperature:
                    type: number
                  averageHumidity:
                    type: number
        500:
          description: Erro no servidor.

  /v1/sensors/mode:
    get:
      tags:
        - sensors
      summary: Obter moda dos dados
      parameters:
        - name: plantid
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Moda calculada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  modeTemperature:
                    type: number
                  modeHumidity:
                    type: number
        500:
          description: Erro no servidor.

  /v1/sensors/median:
    get:
      tags:
        - sensors
      summary: Obter mediana dos dados
      parameters:
        - name: plantid
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Mediana calculada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  medianTemperature:
                    type: number
                  medianHumidity:
                    type: number
        500:
          description: Erro no servidor.

  /v1/sensors/stddev:
    get:
      tags:
        - sensors
      summary: Obter desvio padrão dos dados
      parameters:
        - name: plantid
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Desvio padrão calculado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  stdDevTemperature:
                    type: number
                  stdDevHumidity:
                    type: number
        500:
          description: Erro no servidor.

  /v1/sensors/skewness:
    get:
      tags:
        - sensors
      summary: Obter assimetria dos dados
      parameters:
        - name: plantid
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Assimetria calculada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  skewnessTemperature:
                    type: number
                  skewnessHumidity:
                    type: number
        500:
          description: Erro no servidor.

  /v1/sensors/regression:
    get:
      tags:
        - sensors
      summary: Obter regressão linear dos dados
      parameters:
        - name: plantid
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Regressão linear calculada com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  projectedTemperature:
                    type: number
                  projectedHumidity:
                    type: number
        500:
          description: Erro no servidor.

components:
  schemas:
    UserRequest:
      type: object
      properties:
        name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string

    UserResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    UserLoginResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    ResetPasswordRequest:
      type: object
      properties:
        email:
          type: string
        current_password:
          type: string
        new_password:
          type: string

    PlantRequest:
      type: object
      properties:
        user_id:
          type: string
        name:
          type: string
        type:
          type: string

    PlantResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string

    SensorData:
      type: object
      properties:
        plant_id:
          type: string
        temperature_air:
          type: number
        humidity_air:
          type: number
        soil_moisture:
          type: string
        timestamp:
          type: string
          format: date-time
        week:
          type: integer
