openapi: 3.0.0
info:
  title: Plant.ly API
  version: v1
  description: API para monitoramento de plantas.
servers:
  - url: http://localhost:3030
    description: Servidor local para a API

paths:
  #### Usuários ####
  /v1/users:
    post:
      summary: Cadastrar um novo usuário
      description: Cria um novo usuário e retorna o ID e os dados cadastrados
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nome do usuário
                  example: João da Silva
                email:
                  type: string
                  description: Email do usuário
                  example: joao@email.com
                password:
                  type: string
                  description: Senha do usuário
                  format: password
                  example: SenhaForte123!
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Usuário criado com sucesso!
                  id:
                    type: string
                    example: 64fd87ef7345b

  /v1/users/{id}:
    get:
      summary: Buscar usuário por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Dados do usuário encontrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  plants:
                    type: array
                    items:
                      type: string
        '404':
          description: Usuário não encontrado

  #### Plantas ####
  /v1/plants/user/{user_id}:
    post:
      summary: Cadastrar uma nova planta
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Cebolinha
                type:
                  type: string
                  example: Folhosas
                image:
                  type: string
                  format: base64
      responses:
        '201':
          description: Planta cadastrada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  plant_id:
                    type: string
                  message:
                    type: string

    get:
      summary: Listar plantas do usuário
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Lista de plantas
          content:
            application/json:
              schema:
                type: object
                properties:
                  plants:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        type:
                          type: string
                        image:
                          type: string
                        date_created:
                          type: string
                          format: date-time
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      pages:
                        type: integer
                      hasMore:
                        type: boolean

  /v1/plants/{id}:
    get:
      summary: Buscar planta por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes da planta
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  type:
                    type: string
                  image:
                    type: string
                  date_created:
                    type: string
                    format: date-time
                  user_id:
                    type: string

    delete:
      summary: Deletar uma planta
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Planta deletada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  #### Autenticação ####
  /v1/auth/login:
    post:
      summary: Login de usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login realizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
        '401':
          description: Credenciais inválidas
