openapi: 3.0.0
info:
  title: API de Monitoramento de Plantas
  version: v1
servers:
  - url: http://localhost:3030
    description: Servidor local

paths:

#### Usuários ####
  /usuarios:
    post:
      summary: Criar um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: João da Silva
                email:
                  type: string
                  example: joao@gmail.com
                senha:
                  type: string
                  format: password
                  example: senha123
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: ID do usuário criado
        '400':
          description: Requisição inválida (email já existente)

  /usuarios/{id}/senha:
    patch:
      summary: Atualizar senha do usuário
      parameters:
        - in: path
          name: id
          required: true
          description: ID do usuário
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                  description: Senha atual do usuário
                  format: password
                  example: teste123
                new_password:
                  type: string
                  description: Nova senha do usuário
                  format: password
                  example: Senh@F0rt3
                password_validation:
                  type: string
                  description: Confirmação da nova senha
                  format: password
                  example: Senh@F0rt3
      responses:
        '200':
          description: Senha atualizada com sucesso
        '400':
          description: Requisição inválida (Senhas não coincidem)
        '401':
          description: Usuário não autenticado


#### Plantas ####
  /plantas:
    post:
      summary: Cadastrar uma nova planta
      description: Endpoint para cadastrar uma nova planta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nome da planta
                  example: Cebolinha
                type:
                  type: string
                  description: Tipo da planta
                  enum: [Hortaliça ,Flor, Fruta, Árvore, Arbusto]
      responses:
        '201':
          description: Planta cadastrada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 1b54fg4773
                  name:
                    type: string
                    example: cebolinha
                  type:
                    type: string
                    example: Hortaliça
                  date_created:
                    type: string
                    format: date
                    example: "2024-10-17T23:59:59Z"

    get:
      summary: Listar todas as plantas
      description: Retornar todas as plantas cadastradas
      responses:
        '200':
          description: Lista de plantas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: ID da planta
                      example: 1b54fg4773
                    name:
                      type: string
                      description: Nome da planta
                      example: cebolinha
                    type:
                      type: string
                      description: Tipo da planta
                      example: Hotaliça
                    date_created:
                      type: string
                      format: date
                      example: "2024-10-17T23:59:59Z"
  
  /plantas/{id}:
    get:
      summary: Obter detalhes de uma planta
      parameters:
        - in: path
          name: id
          required: true
          description: ID da planta
          schema:
            type: string
      responses:
        '200':
          description: Detalhes da planta
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 1b54fg4773
                  name:
                    type: string
                    example: cebolinha
                  type:
                    type: string
                    example: Hortaliça
                  date_created:
                    type: string
                    format: date
                    example: "2024-10-17T23:59:59Z"
        '404':
          description: Planta não encontrada

    delete:
      summary: Excluir uma planta
      parameters:
        - in: path
          name: id
          required: true
          description: ID da planta
          schema:
            type: string
      responses:
        '204':
          description: Planta excluída com sucesso
        '404':
          description: Planta não encontrada
  
#### Sensores ####  
  /sensores:
    get:
      summary: Buscar dados de sensores
      description: Retornar dados dos sensores filtrados por planta e outros critérios como data, temperatura e umidade.
      parameters:
        - name: plant
          in: query
          required: true
          description: Nome da planta a ser filtrada
          schema:
            type: string
            example: cebolinha
        - name: start_date
          in: query
          required: false
          description: Data inicial para filtrar os registros (formato ISO 8601)
          schema:
            type: string
            format: date-time
            example: "2024-10-01T00:00:00Z"
        - name: end_date
          in: query
          required: false
          description: Data final para filtrar os registros (formato ISO 8601)
          schema:
            type: string
            format: date-time
            example: "2024-10-17T23:59:59Z"
        - name: temperature_min
          in: query
          required: false
          description: Temperatura mínima para filtrar os registros
          schema:
            type: number
            example: 20.0
        - name: temperature_max
          in: query
          required: false
          description: Temperatura máxima para filtrar os registros
          schema:
            type: number
            example: 30.0
        - name: humidity_min
          in: query
          required: false
          description: Umidade mínima do ar para filtrar os registros
          schema:
            type: number
            example: 40.0
        - name: humidity_max
          in: query
          required: false
          description: Umidade máxima do ar para filtrar os registros
          schema:
            type: number
            example: 70.0
        - name: soil_moisture_status
          in: query
          required: false
          description: Status da umidade do solo (seco, úmido, etc.)
          schema:
            type: string
            example: Úmido
      responses:
        '200':
          description: Lista de dados dos sensores filtrados
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    plant:
                      type: string
                      description: Nome da planta monitorada
                      example: Cebolinha
                    temperature_air_celsius:
                      type: number
                      description: Temperatura do ar em graus Celsius
                      example: 26.7
                    humidity_air_percentage:
                      type: number
                      description: Umidade do ar em porcentagem
                      example: 54.4
                    soil_moisture_status:
                      type: string
                      description: Status da umidade do solo (seco, úmido, etc.)
                      example: Úmido
                    timestamp:
                      type: string
                      format: date-time
                      description: Data e hora do registro
                      example: "2024-10-17T03:28:11Z"
                    week:
                      type: integer
                      description: Semana desde o início do monitoramento
                      example: 1
        '400':
          description: Erro de validação dos parâmetros
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Parâmetros inválidos