services:
  - type: web
    name: plantly-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
